# Generated by Django 3.2.9 on 2021-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teksti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsikko', models.CharField(default='', max_length=100)),
                ('teksti', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
